### ISSUE TITLE
Not working with node 0.6 ?

### ISSUE THREAD

**Issue by temsa** [stolsma/intercom#1]
It seems that node-fork does not work with 0.6.x, so intercom neither :'(

I tried to force-install it with a "npm install --force", node-fork compiles, but even if I should not care about it in 0.6.x, it seems to be used by intercom so it doesn't work. Maybe it should only be loaded if necessary ?

**Comment by stolsma** [comment]
Yep, you are right. Didn't have time to check compatibility until now but intercom should work without node-fork. Probably it tries to `require` node-fork even when it doesn't need it. the `require` fails because node-fork didn't compile correctly and isn't there...

I'm totally swamped with (management) work at the moment, will try to solve this on Sunday but I will accept a pull request if you find a solution.. ;-)

**Comment by temsa** [comment]
If I can get some time on it before Sunday, I will :)

**Comment by stolsma** [comment]
Found the problem and more or less fixed in master branch. This fix makes Intercom run under 0.6.x BUT child stdout and stderr redirect had to be taken out.

I also need to fix node-fork for compiling under 0.6.x. Install Intercom now with force: `npm install --force` until I fix that...

I will be working on the stdout/stderr redirect and node-fork compiling the next week but the master branch will give you possibility to use Intercom with 0.6.x already.

Hope this will help you on the short term?

**Comment by stolsma** [comment]
Ok, it looks like the current master branch is now node v0.6x compatible. The only problem that still has to be solved is the stderr and stdout redirect options. Will bump the version and put the package on NPM when I solved that problem.

**Comment by stolsma** [comment]
Did some rewriting to node-fork and solved the stdout and stderr redirect problem for node 0.6.x.After that I pushed some final changes to Intercom and bumped the version to 0.3.0.

Closing this issue, thanks for opening it!

**Comment by temsa** [comment]
Could not test it yet, but I'm glad you fixed it, I'll can continue to work with it =)
